#-------------------------------
# General Site Settings

title: N3VEM | openShack Blog
description: Giving the world a peek into my hamshack 
# this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # needs changed to the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Vance Martin
author-avatar: logosmall.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/n3vem # Add your Facebook handle
twitter:   https://twitter.com/n3vem # Add your Facebook handle
instagram: https://www.instagram.com/n3vem # Add your Facebook handle
pinterest: https://www.pinterest.com/vanceem # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: n3vem # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-75046129-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: eepurl.com/c3T4Nj # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

redirect_from:
  json: false
#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
